// Generated by CoffeeScript 1.3.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

(function($) {
  var views;
  views = require('views');
  views.Home = (function(_super) {

    __extends(Home, _super);

    Home.name = 'Home';

    function Home() {
      return Home.__super__.constructor.apply(this, arguments);
    }

    Home.prototype.prepare = function() {
      return this.template = this._requireTemplate('views/html/home.html');
    };

    Home.prototype.renderView = function() {
      return this.el.html(this.template.render());
    };

    return Home;

  })(views.Page);
  return $.route.add({
    '': function(type) {
      return $('#content').view({
        name: 'Home'
      });
    }
  });
})(ender);
