"""Shared loader for `.codeyam/cache/step-metadata.json`.

Both `editor-step-hook.py` (PostToolUse / Stop / UserPromptSubmit) and
`editor-pretool-hook.py` (PreToolUse) read this cache. Keeping a single
implementation here means a schema change is a one-file edit.

The cache is regenerated by `codeyam-editor editor verify-build`,
which is wired into the audit gate, the advance gate, and the
embedded pre-commit hook. Schema versions 1 (label/description/
restriction only), 2 (adds slug + capability tag projections), and 3
(adds the per-phase `testRunSlugs` projection, plus its additive
`noTestSlugs` companion) all load successfully; callers see empty
arrays for any projection an older cache omits so the hook degrades to
"allow everything" rather than blocking on a stale cache after a binary
downgrade.

`SUPPORTED_SCHEMA_VERSIONS` is a CLOSED set: an unrecognized (including
NEWER) version falls back to empty tables, which drops every gate — the
commit and push gates included, not just the projection that changed.
That asymmetry is why a purely additive projection like `noTestSlugs`
lands inside v3 rather than bumping to v4: a new binary paired with an
older shipped hook copy then degrades one message, not the whole gate
layer.
"""

import json
import os


CACHE_REL_PATH = os.path.join(".codeyam", "cache", "step-metadata.json")

SUPPORTED_SCHEMA_VERSIONS = (1, 2, 3)


def cli_command():
    """Return the codeyam-editor CLI name to surface to the user.

    Canonical `codeyam-editor` unless the caller explicitly opted into
    the dev branding via `CODEYAM_CLI`. `npm/editor-dev.js` sets that
    variable ONLY when it was invoked as `codeyam-editor-dev`, and
    deliberately leaves it unset behind the `codeyam-editor` symlink.

    This must NOT probe PATH for `codeyam-editor-dev`. `scripts/
    bootstrap.sh` symlinks the dev wrapper under BOTH names, so on any
    local-dev checkout the probe always finds it and every hook then
    emits `-dev` — including for the developer who invoked the canonical
    name and the shipped output that reaches clients. CLAUDE.md's rule
    is that shipped hooks emit `codeyam-editor` and never
    `codeyam-editor-dev`; an env var the wrapper sets is the only signal
    that actually distinguishes the two invocations.
    """
    override = os.environ.get("CODEYAM_CLI", "").strip()
    # A stray empty `CODEYAM_CLI=` must not emit an empty command into
    # every hint — fall back to the canonical name.
    if override:
        return override
    return "codeyam-editor"


# How each shipped mode names its flow in the banner the user reads every
# turn. `ui` and `backend` are builds and say "Flow"; `assist` and `design`
# are not, and saying "Flow" for them would re-assert the very thing the
# tracks exist to avoid.
_MODE_DISPLAY_PREFIXES = {
    "ui": "UI Flow",
    "backend": "Backend Flow",
    "assist": "Assist",
    "design": "Design Round",
}


def mode_display_prefix(mode):
    """The banner prefix for `mode` — `Assist` for an assist session,
    `Backend Flow` for a backend build, and so on.

    An unrecognized mode renders as its own title-cased name rather than
    defaulting to `UI Flow`. The default was a lie the user read on every
    prompt: an assist session announced itself as `UI Flow Step 1/28
    (Plan)` and then told the agent "Do NOT skip ahead" on a track that
    has four steps and no plan. A mode the emitter ships tomorrow should
    misspell its own name at worst, never claim to be a different
    workflow."""
    if not isinstance(mode, str) or not mode.strip():
        return _MODE_DISPLAY_PREFIXES["ui"]
    known = _MODE_DISPLAY_PREFIXES.get(mode)
    if known:
        return known
    return mode.replace("-", " ").replace("_", " ").title()


# The modes that are NOT builds. `assist` triages a non-build request and
# `design` explores mockups; neither is walking a build to completion, so
# build-flow framing ("do not skip ahead") is a false statement about the
# session rather than a useful guardrail.
#
# Enumerated as the NON-build set, not the build set, so the default for an
# unrecognized mode is "build" — see `mode_is_build`.
_NON_BUILD_MODES = frozenset(("assist", "design"))


def mode_is_build(mode):
    """True when `mode` walks a build flow to completion.

    Unknown modes count as builds. That is the conservative direction: the
    guardrail copy is kept rather than dropped for a mode this hook copy
    has never heard of, so a newer emitter can never silently relax a real
    build flow's framing against an older shipped hook."""
    if not isinstance(mode, str) or not mode.strip():
        return True
    return mode not in _NON_BUILD_MODES


def _empty_mode_table():
    return {
        "total": 0,
        "labels": {},
        "descriptions": {},
        "restrictions": {},
        "slugsByStep": {},
        "codeChangeSlugs": [],
        "commitSlugs": [],
        "pushSlugs": [],
        "previewRequiredSlugs": [],
        "testRunSlugs": [],
        "noTestSlugs": {},
    }


def _kv_pairs_to_int_dict(pairs):
    """Cache mode-table fields are JSON arrays of [step, value] pairs.
    Convert to {int(step): value} for O(1) lookup."""
    out = {}
    for entry in pairs or []:
        try:
            step_num, value = entry
            out[int(step_num)] = value
        except (TypeError, ValueError):
            continue
    return out


def _string_list(raw):
    """Normalize a JSON value to a list[str]. Non-list inputs and
    non-string members are dropped — the hook treats malformed entries
    as if they were absent rather than blocking on parse error."""
    if not isinstance(raw, list):
        return []
    return [s for s in raw if isinstance(s, str)]


def _no_test_slug_map(raw):
    """Normalize the `noTestSlugs` projection to {slug: {kind, nextTestRunSlug}}.

    The cache carries it as a list of objects; a dict keyed by slug is what
    the hook actually looks up. Malformed members are dropped rather than
    raised on — a slug with no entry reads as "word the block the old way",
    which is the same status-quo degrade an absent projection gets."""
    out = {}
    if not isinstance(raw, list):
        return out
    for entry in raw:
        if not isinstance(entry, dict):
            continue
        slug = entry.get("slug")
        kind = entry.get("kind")
        if not isinstance(slug, str) or not isinstance(kind, str):
            continue
        next_slug = entry.get("nextTestRunSlug")
        out[slug] = {
            "kind": kind,
            "nextTestRunSlug": next_slug if isinstance(next_slug, str) else None,
        }
    return out


def load_step_metadata(project_dir):
    """Load the per-mode step metadata cache. Returns
    {<mode name>: <mode_table>} — one entry per mode the cache
    actually carries — where each mode_table carries label/
    description/restriction dicts plus slug-keyed capability arrays.

    The mode set is ENUMERATED FROM THE DOCUMENT, not hard-coded. The
    Rust emitter ships `assist` and `design` tables alongside `ui` and
    `backend`, and a hard-coded `("ui", "backend")` pair dropped them on
    the floor — which is what made an assist session load the UI table,
    be labeled `UI Flow Step 1/28`, and have its commit refused at
    `assist-wrap` because the UI table's `commitSlugs` is `["commit"]`.
    Reading the keys off the document means the next mode the emitter
    ships is picked up with no edit here.

    Falls back to empty tables on any read/parse error so the hook
    keeps firing (just without labels and with no slug allowlists)
    when the cache is missing or a different binary version wrote a
    shape we don't understand. Empty capability arrays mean the
    pretool hook treats every slug as ungated — degrade to "allow"
    rather than brick the session on cache skew."""
    cache_path = os.path.join(project_dir, CACHE_REL_PATH)
    fallback = {"ui": _empty_mode_table(), "backend": _empty_mode_table()}
    try:
        with open(cache_path, "r") as f:
            raw = json.load(f)
    except (IOError, json.JSONDecodeError):
        return fallback
    if not isinstance(raw, dict) or raw.get("schemaVersion") not in SUPPORTED_SCHEMA_VERSIONS:
        return fallback
    out = {}
    for mode_key, mode_raw in raw.items():
        # `schemaVersion` is the one non-mode top-level key. Guarding on
        # the VALUE's type rather than a name denylist means any future
        # scalar sibling is skipped too, instead of being normalized into
        # a bogus mode table.
        if mode_key == "schemaVersion" or not isinstance(mode_raw, dict):
            continue
        out[mode_key] = {
            "total": int(mode_raw.get("total", 0) or 0),
            "labels": _kv_pairs_to_int_dict(mode_raw.get("labels", [])),
            "descriptions": _kv_pairs_to_int_dict(mode_raw.get("descriptions", [])),
            "restrictions": _kv_pairs_to_int_dict(mode_raw.get("restrictions", [])),
            "slugsByStep": _kv_pairs_to_int_dict(mode_raw.get("slugsByStep", [])),
            "codeChangeSlugs": _string_list(mode_raw.get("codeChangeSlugs")),
            "commitSlugs": _string_list(mode_raw.get("commitSlugs")),
            "pushSlugs": _string_list(mode_raw.get("pushSlugs")),
            "previewRequiredSlugs": _string_list(mode_raw.get("previewRequiredSlugs")),
            # v3 projection. Absent in a v1/v2 cache → empty list → the
            # pretool hook treats test runs as ungated (degrade to "allow"),
            # never "block every test run".
            "testRunSlugs": _string_list(mode_raw.get("testRunSlugs")),
            # Companion to `testRunSlugs`, added additively WITHIN v3 (a
            # version bump would make this closed `SUPPORTED_SCHEMA_VERSIONS`
            # tuple reject a newer cache outright and drop every gate).
            # Absent → empty map → the pretool hook falls back to its
            # original pre-Demo wording.
            "noTestSlugs": _no_test_slug_map(mode_raw.get("noTestSlugs")),
        }
    return out


def resolve_mode_table(state, metadata):
    """Pick the mode table matching the active state, by name.

    Defaults to UI when `mode` is MISSING — matches the legacy behavior
    where state files predating multi-mode support are treated as UI
    sessions.

    A mode that is named but has no table in the cache returns an EMPTY
    table, not the UI one. Substituting UI was the previous behavior and
    it is the bug this fixes in miniature: it does not degrade to "no
    gating", it silently applies a DIFFERENT workflow's gates — the UI
    flow's 28 steps, restrictions, and `commitSlugs` — to a session that
    is not a UI build. An empty table means "no gating", which is the
    documented degrade-to-allow contract."""
    mode = (state.get("mode") or "ui") if isinstance(state, dict) else "ui"
    table = metadata.get(mode)
    if isinstance(table, dict):
        return mode, table
    return mode, _empty_mode_table()
