// Generated by CoffeeScript 1.3.1
var express, fs, router, url;

fs = require('fs');

url = require('url');

express = require('express');

router = require('./lib/router');

router.init(function() {
  var app;
  require('./api/user');
  app = express.createServer();
  app.configure(function() {
    app.use(express["static"](__dirname + '/../public'));
    return app.use(express.errorHandler({
      dumpExceptions: true,
      showStack: true
    }));
  });
  app.get('/api/*', function(req, res) {
    var context;
    context = router.handle(req, res);
    return context.emit('route');
  });
  app.listen(process.env.PORT || 5000);
  return console.log("Listening on port " + (process.env.PORT || 5000));
});
