// Generated by CoffeeScript 1.3.3

window.app = {
  initialize: function() {
    var languageScramble,
      _this = this;
    languageScramble = require('./lib/language_scramble');
    this.selector = $('.scramble_content');
    this.puzzleData = JSON.parse(window.localStorage.getItem('data')) || {
      levels: {}
    };
    this.puzzleData = {
      "levels": {
        "english_italian": {
          "top10words": {
            "is-_": 1,
            "and-e": 2,
            "percentComplete": 14.285714285714278,
            "the-il": 2,
            "of-di": 1,
            "a-un": 2,
            "not-non": 2,
            "are-sono": 2
          }
        }
      },
      "lastLevelPlayed": "top10words"
    };
    this.languages = "english_italian";
    this.levelName = "top10words";
    if (!this.puzzleData.levels[this.languages]) {
      this.puzzleData.levels[this.languages] = {};
    }
    this.viewHelper = new languageScramble.ViewHelper({
      el: $(this.selector),
      puzzleData: this.puzzleData,
      languages: this.languages,
      saveProgress: function(puzzleProgress) {
        return _this.saveProgress(puzzleProgress);
      }
    });
    this.initProgressMeter();
    this.viewHelper.setLevel(this.levelName);
    this.viewHelper.bindWindow();
    this.viewHelper.bindKeyPress();
    return this.viewHelper.newScramble();
  },
  initProgressMeter: function() {
    this.progressMeter = this.viewHelper.$('.level_progress_meter');
    this.percentComplete = this.progressMeter.find('.percent_complete');
    return this.progressMeter.css({
      top: window.innerHeight - this.percentComplete.height()
    });
  },
  saveProgress: function(puzzleProgress) {
    var _ref;
    if ((_ref = puzzleProgress.levels[this.languages][this.levelName]) != null ? _ref.percentComplete : void 0) {
      this.percentComplete.width("" + puzzleProgress.levels[this.languages][this.levelName].percentComplete + "%");
    }
    return window.localStorage.setItem("data", JSON.stringify(puzzleProgress));
  }
};
